<?php

namespace Database\Seeders;

use App\Models\RecConfession;
use Illuminate\Database\Seeder;

class RecConfessionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        RecConfession::insert([
            [
                "id_confession" => 1,
                "date" => now(),
                "title" => "Digerebek di Gudang",
                "slug" => "digerebek-di-gudang",
                "body" => "Ada yang bisa ngebantu gak? Kemaren gue lagi sendirian di gudang, eh tiba-tiba ada orang masuk. Gue nggak tau siapa itu, mukanya ditutupin. Terus dia ngancem-ngancem gitu, kayak mau ngapain gitu. Gue langsung kaget parah, ya ampun! Udah gitu, dia ngacir aja gitu, gue sampe nggak bisa ngapa-ngapain. Ada yang punya info gak siapa itu?",
                "excerpt" => "Ada yang bisa ngebantu gak? Kemaren gue lagi sendirian di gudang ...",
                "place" => "in",
                "status" => "process",
                "privacy" => "anonymous",
                "created_at" => now(),
                "id_confession_category" => 1,
                "id_user" => 3,
                "assigned_to" => 9,
            ],
            [
                "id_confession" => 2,
                "date" => now(),
                "title" => "Siapa Sih Yang Nge-Steal Kotak Pensil Gw?",
                "slug" => "siapa-sih-yang-nge-steal-kotak-pensil-gw",
                "body" => "Nih gw udah cari kotak pensil gw dari kemarin-kemarin. Padahal, isinya pensil warna yang udah gw kumpulin dari TK, bisa dibayangin gimana berharganya buat gw. Udah gw tanya sana-sini, tapi belum ketemu juga. Kalo loe yang ambil, tolong balikin ya, gw janji gak bakal marah-marah.",
                "excerpt" => "Nih gw udah cari kotak pensil gw dari kemarin-kemarin. Padahal, isinya  ...",
                "place" => "in",
                "status" => "unprocess",
                "privacy" => "public",
                "created_at" => now(),
                "id_confession_category" => 5,
                "id_user" => 5,
                "assigned_to" => null,
            ],
            [
                "id_confession" => 3,
                "date" => now(),
                "title" => "Guru Favorit Sy Kepincut Sama Gebetan Sy Sendiri :(",
                "slug" => "guru-favorit-sy-kepincut-sama-gebetan-sy-sendiri",
                "body" => "Jadi ceritanya gini, sy suka sama cowok di kelas yang sy tau dia juga suka sama sy. Tapi tau gak, guru favorit sy malah nge-chase dia. Sy bingung deh, gimana caranya biar sy bisa nge-jaga hati gebetan sy dari guru itu tanpa bikin ribet di sekolah.",
                "excerpt" => "Jadi ceritanya gini, sy suka sama ...",
                "place" => "in",
                "status" => "unprocess",
                "privacy" => "anonymous",
                "created_at" => now(),
                "id_confession_category" => 5,
                "id_user" => 4,
                "assigned_to" => null,
            ],
            [
                "id_confession" => 4,
                "date" => now(),
                "title" => "Cowok Sy Malah Jadi Stalker",
                "slug" => "cowok-sy-malah-jadi-stalker",
                "body" => "Kenapa ya cowok sy jadi kayak stalker? Udah sy bilangin biar gak kepo terus, tapi dia tetep aja nyelipin diri di mana-mana. Sy ngerasa udah keganggu banget sama sikapnya, tapi sy juga sayang sama dia. Sy butuh saran nih, gimana caranya biar dia ngertiin tanpa harus sy putusin.",
                "excerpt" => "Kenapa ya cowok sy jadi kayak ...",
                "place" => "in",
                "status" => "unprocess",
                "privacy" => "anonymous",
                "created_at" => now(),
                "id_confession_category" => 6,
                "id_user" => 4,
                "assigned_to" => null,
            ],
            [
                "id_confession" => 5,
                "date" => now(),
                "title" => "Pegang-pegang Terus di Angkot",
                "slug" => "pegang-pegang-terus-di-angkot",
                "body" => "Duh, aku bener-bener kesel banget tadi pagi. Lagi naik angkot, eh ada cowok yang duduk di sebelah aku terus pegang-pegang mulu. Aku sudah menjauh, malah makin nekat. Ya ampun, bener-bener nggak nyaman banget. Ada yang tau gimana caranya ngelawan gitu?",
                "excerpt" => "Duh, aku bener-bener kesel banget tadi pagi. Lagi naik angkot, eh ...",
                "place" => "out",
                "status" => "unprocess",
                "privacy" => "anonymous",
                "created_at" => now(),
                "id_confession_category" => 2,
                "id_user" => 5,
                "assigned_to" => 10,
            ],
            [
                "id_confession" => 6,
                "date" => now(),
                "title" => "Dibikin Malu di Depan Kelas",
                "slug" => "dibikin-malu-di-depan-kelas",
                "body" => "Ceritanya gini, tadi siang gw lagi ngopi di kantin, eh tiba-tiba ada temen yang sebut aja inisialnya si Yudis. Dia dateng terus ngomong di depan semua orang kalo gw tuh abis beli minum tapi nggak punya duit. Padahal, itu boong banget! Gw bingung, malu banget deh. Ada yang bisa bantu ngadain pembalasan yang baik?",
                "excerpt" => "Ceritanya gini, tadi siang gw lagi ...",
                "place" => "in",
                "status" => "unprocess",
                "privacy" => "public",
                "created_at" => now(),
                "id_confession_category" => 5,
                "id_user" => 3,
                "assigned_to" => null,
            ],
            [
                "id_confession" => 7,
                "date" => now(),
                "title" => "Guru Galak Banget, Susah Diakalin",
                "slug" => "guru-galak-banget-susah-diakalin",
                "body" => "Kalian tau si guru slepet yang galak itu kan? Bener-bener kayak t-rex kalau lagi marah. Gw kayak mimpi buruk tiap kali masuk kelas dia. Ada yang punya trik jitu supaya dia bisa lebih manusiawi dan nggak nge-bully murid lagi?",
                "excerpt" => "Kalian tau si guru slepet yang galak itu kan? Bener-bener kayak ...",
                "place" => "in",
                "status" => "unprocess",
                "privacy" => "public",
                "created_at" => now(),
                "id_confession_category" => 1,
                "id_user" => 3,
                "assigned_to" => null,
            ],
            [
                "id_confession" => 8,
                "date" => now(),
                "title" => "Guru Ngomongin Privasi Murid di Kelas",
                "slug" => "guru-ngomongin-privasi-murid-di-kelas",
                "body" => "Guru gw tuh suka banget ngomongin privasi murid di kelas. Gw bener-bener nggak nyaman banget. Udah gitu, dia juga suka nge-bully murid-murid yang dia anggap jelek. Gw bingung, gimana caranya biar dia nggak kayak gitu lagi?",
                "excerpt" => "Guru gw tuh suka banget ngomongin privasi murid di kelas. Gw bener-bener nggak nyaman banget ...",
                "place" => "in",
                "status" => "unprocess",
                "privacy" => "public",
                "created_at" => now(),
                "id_confession_category" => 1,
                "id_user" => 3,
                "assigned_to" => null,
            ],
            [
                "id_confession" => 9,
                "date" => now(),
                "title" => "Sering Ditindas Karena Hobinya Unik",
                "slug" => "sering-ditindas-karena-hobinya-unik",
                "body" => 'Gw punya hobi yang agak lain, yaitu suka koleksi kambing. Tapi temen-temen gw malah nyebut gw "dasar pemain Genshin Impact" dan ngejek hobi gw. Gw udah capek ngadepin bully-an mereka. Ada yang punya cara supaya gw bisa tetep enjoy hobi tanpa dibilang aneh?',
                "excerpt" => "Gw punya hobi yang agak beda dari yang lain, yaitu suka ...",
                "place" => "in",
                "status" => "unprocess",
                "privacy" => "public",
                "created_at" => now(),
                "id_confession_category" => 3,
                "id_user" => 3,
                "assigned_to" => null,
            ],
            [
                "id_confession" => 10,
                "date" => now(),
                "title" => "Nge-Bully Itu Nggak Keren, Sumpah!",
                "slug" => "nge-bully-itu-nggak-keren-sumpah",
                "body" => "Gue punya temen cewek di kelas, tiap hari dia di-bully sama anak-anak yang sok jago. Gak tau kenapa sih mereka suka banget nyinyirin dia. Udah sering banget gue dengerin dia nangis di kamar mandi. Padahal, kan gak ada alasan buat nge-bully orang. Sekarang gue bingung, gimana caranya ngadepin ini biar temen gue gak makin down.",
                "excerpt" => "Gue punya temen cewek di kelas, tiap hari dia di-bully sama anak-anak yang ...",
                "place" => "in",
                "status" => "unprocess",
                "privacy" => "anonymous",
                "created_at" => now(),
                "id_confession_category" => 3,
                "id_user" => 3,
                "assigned_to" => null,
            ],
        ]);
    }
}
